### ISSUE TITLE
Interpret the extracted data from images

### ISSUE THREAD

**Issue by almutareb** [almutareb/mail_automation_wf#15]
**Is your feature request related to a problem? Please describe.**
The OCR extracted data can be a bit messy, using an LLM to make sense of it is a good start but should be improved

**Describe the solution you'd like**
Make sure to recognize the entities, insured, claimer, accident, etc. correctly

**Describe alternatives you've considered**
- Use proximity of the content to determine its relation
- Use empty form to identify relation of questions and answers
- Create special forms for this: determine what is needed for a reliable solution (structure, style, marks, color coding, etc.)

**Additional context**
Determining what data belongs together is important for a reliable outcome, how can we improve it as much as possible: can we find an approach to use existing forms? Do we need specially designed forms?

**Comment by isayahc** [comment]
I need to create a method for DocumentParser that will create a Json representation of a page. 

```
    try: 
        ocr_json = extract_json_from_string(temp_data_name[0])
        print("pre-processing document was successful")
    except:
        print("Issue pre parsing the json")
        
    try:
        ocr_json = json_string_to_json(temp_data_name[0])
        print("Sucessful without preproccessing")
    except:
        print("parsing unsuccessfull")
```
